import { Product } from '@/types/product';

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: 'lx-01',
    name: 'Vortex Quantum Core',
    tagline: 'Self-levitating kinetic art with luminescent core',
    description: 'Precision SLA printed using aerospace resin and magnetic induction levitation. Engineered for futuristic desktops and ambient lighting.',
    price: 189,
    originalPrice: 249,
    category: 'Desk Art',
    rating: 4.9,
    reviewsCount: 142,
    badge: 'Best Seller',
    image: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=800&auto=format&fit=crop&q=80',
    geometryType: 'torus',
    inStock: true,
    specs: {
      material: 'Titanium-Infused SLA Photopolymer',
      resolution: '25 Microns',
      finish: 'Matte Obsidian & Neon Glow',
      dimensions: '140mm x 140mm x 165mm',
    },
  },
  {
    id: 'lx-02',
    name: 'Cybernetic Neural Visor',
    tagline: 'Ergonomic HUD wearable with dual prismatic optics',
    description: 'Custom fitted parametric wearable visor crafted with ultra-light carbon lattice. Features anti-glare chromatic shields.',
    price: 349,
    originalPrice: 420,
    category: 'Wearables',
    rating: 5.0,
    reviewsCount: 88,
    badge: 'Limited Edition',
    image: 'https://images.unsplash.com/photo-1593508512255-86ab42a8e620?w=800&auto=format&fit=crop&q=80',
    geometryType: 'headset',
    inStock: true,
    specs: {
      material: 'Carbon Fiber & Aerospace TPU',
      resolution: '12 Microns Micro-SLA',
      finish: 'Iridescent Cyber Chrome',
      dimensions: 'Custom Head Contour Fit',
    },
  },
  {
    id: 'lx-03',
    name: 'Hyper-Tesseract Desk Artifact',
    tagline: '4D geometrical projection frozen in optical glass',
    description: 'Laser etched internal fractal geometry combined with a high-strength sintered nylon exterior cage.',
    price: 129,
    originalPrice: 160,
    category: 'Desk Art',
    rating: 4.8,
    reviewsCount: 204,
    badge: '3D Interactive',
    image: 'https://images.unsplash.com/photo-1634017839464-5c339ebe3cb4?w=800&auto=format&fit=crop&q=80',
    geometryType: 'cyber-cube',
    inStock: true,
    specs: {
      material: 'Selective Laser Sintered (SLS) Nylon PA12',
      resolution: '60 Microns',
      finish: 'Vapor Polished Satin',
      dimensions: '110mm x 110mm x 110mm',
    },
  },
  {
    id: 'lx-04',
    name: 'Aero-Lattice Mech Gauntlet',
    tagline: 'Articulated biometric cybernetic forearm brace',
    description: 'Generative design optimized for minimal weight and maximum torsional resistance. Features magnetic snap hinges.',
    price: 499,
    category: 'Cyber Gear',
    rating: 4.9,
    reviewsCount: 63,
    badge: 'New Arrival',
    image: 'https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?w=800&auto=format&fit=crop&q=80',
    geometryType: 'prism',
    inStock: true,
    specs: {
      material: 'Direct Metal Laser Sintered AlSi10Mg',
      resolution: '30 Microns',
      finish: 'Bead-Blasted Gunmetal',
      dimensions: 'Modular Link Size S/M/L',
    },
  },
  {
    id: 'lx-05',
    name: 'Orbital Chrono Sphere',
    tagline: 'Gyroscopic perpetual desk timepiece',
    description: 'Multi-axis gimbal rings with micro ball bearings that spin silently with atmospheric breezes or a slight touch.',
    price: 219,
    originalPrice: 279,
    category: 'Collectibles',
    rating: 4.9,
    reviewsCount: 119,
    badge: 'Best Seller',
    image: 'https://images.unsplash.com/photo-1508739773434-c26b3d09e071?w=800&auto=format&fit=crop&q=80',
    geometryType: 'sphere',
    inStock: true,
    specs: {
      material: 'Solid Brass & 3D Printed Steel Matrix',
      resolution: '40 Microns',
      finish: 'Anodized Midnight Azure',
      dimensions: '130mm Diameter Sphere',
    },
  },
  {
    id: 'lx-06',
    name: 'Modular Cyber Blade Keypad',
    tagline: 'Parametric split ergonomic mechanical controller',
    description: 'Hot-swappable tactile switches embedded in an acoustic dampening hollow matrix shell with RGB underglow channels.',
    price: 279,
    category: 'Cyber Gear',
    rating: 4.7,
    reviewsCount: 75,
    badge: '3D Interactive',
    image: 'https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=800&auto=format&fit=crop&q=80',
    geometryType: 'cyber-cube',
    inStock: true,
    specs: {
      material: 'Reinforced Ceramic Resin Composite',
      resolution: '20 Microns',
      finish: 'Ghost White Ceramic Texture',
      dimensions: '160mm x 120mm x 35mm per half',
    },
  },
];
